### ISSUE TITLE
Subdomain cookie

### ISSUE THREAD

**Issue by karimhb** [paragi/sphp#14]
There is no way of setting cookies at .domain (DotDomain), cookies are always set at domain.com (without the dot).

     `setcookie("AAA", "value" -1, '/', ".domain.com"); // is set at domain.com`

**Comment by paragi** [comment]
Thank you for taking time to write me.
I assume that a comma is missing in your test case:
setcookie("AAA", "value", -1, '/', ".domain.com")

As I understand it, the use of a leading “.” to match all subdomains, is a deprecated practise in most browsers.

Would you be so kind as to describe a setup, where this can be tested with an actual effect?

**Comment by karimhb** [comment]
Thanks for your reply paragi. I don't believe there is a missing comma. The cookie gets set but to the wrong domain. There is no way of setting a cookie to all subdomains with or without the dot. The same line creates a cookie on .domain.com when executed without sphp out of the node environment on the same server.

Other than this issue sphp has been very helpful. Thanks you.

**Comment by paragi** [comment]
Hi karimhb

I don't understand the meaning of this: `"value" -1 `in your example.
Domain is the 5th parameter of the setcookie function. You only specify 4.
This would result in that the cookie uses the default domain.

This is from the PHP manual:
> The (sub)domain that the cookie is available to. Setting this to a subdomain (such as 'www.example.com') will make the cookie available to that subdomain and all other sub-domains of it (i.e. w2.www.example.com). To make the cookie available to the whole domain (including all subdomains of it), simply set the value to the domain name ('example.com', in this case).
>  Older browsers still implementing the deprecated » RFC 2109 may require a leading . to match all subdomains.

Do you disagree with this? 

I would like to be very clear about this, before commenting time and resources. 
Before solving an issue, its important to know that its the right issue to solve :)

**Comment by karimhb** [comment]
Not disagreeing at all.

-1 is the timestamp, commonly used to delete a cookie, it doesn't affect
the issue I'm talking about. The bug also exists with a future positive
timestamp.

Setting a cookie directly on php on the same server on sub.domain.com
results in a ".domain.com" cookie. With sphp the same line results in the
cookie being set on "sub.domain.com".

Setting a cookie on ".domain.com" or not including the domain at all, in
php sets the cookie on ".domain.com" while sphp sets it on "domain.com" in
both cases.

There is no possible way to set a cookie to be available to all subdomains
using sphp.



On 10 Mar. 2018 10:42 am, "Simon Rigét" <notifications@github.com> wrote:

Hi karimhb

I don't understand the meaning of this: "value" -1 in your example.
Domain is the 5th parameter of the setcookie function. You only specify 4.
This would result in that the cookie could specify the default domain.

This is from the PHP manual:

The (sub)domain that the cookie is available to. Setting this to a
subdomain (such as 'www.example.com') will make the cookie available to
that subdomain and all other sub-domains of it (i.e. w2.www.example.com).
To make the cookie available to the whole domain (including all subdomains
of it), simply set the value to the domain name ('example.com', in this
case).
Older browsers still implementing the deprecated » RFC 2109 may require a
leading . to match all subdomains.

Do you disagree with this?

Before solving an issue, its important to know that its the right issue to
solve :)
I would like to be very clear about this, before commenting time and
resources.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/paragi/sphp/issues/14#issuecomment-372013914>, or mute
the thread

**Comment by Apollon77** [comment]
I also think you missed a comma. 
Please try it with the correct call and if possible please post the resulting header (ideally with the cookie header in it) when called as php directly. I think this helps to dig into it.

**Comment by karimhb** [comment]
I'm trying to help out and letting you know about an obvious bug. I don't
have time to debug sphp unfortunately.

**Comment by Apollon77** [comment]
No one say that you should Debug sphp! But you should have an own interest to support us in solving your issue. 

If you want us investigating you should show in this case that your code produces valid results in a plain php context without sphp. 

Official php definition for setCookie: http://php.net/manual/de/function.setcookie.php ... 
We think that your call is wrong and it would create a wrong cookie even outside of sphp usage. We want to make first sure that this is not the reason at all. 

Do please check your code and that it is correct usage of the function and for this we ask for the header output of php when your script is called outside of sphp. 

Thank you for your support.

**Comment by karimhb** [comment]
As I mentioned a clone of the code gives different results on plain php on
the same server.

I am only reporting this bug to you because I like sphp and not looking for
a resolution. I I hope that helps.

**Comment by Apollon77** [comment]
When you can see different result then please provide the different headers send by the server to the Browser for with and without sphp. This can speed up a fix. 

Else we needs to build a scrimmage t and try to reproduce it and only then we would see if it is a bug or a false positive because of your code (i will not repeat the question on that from above)

**Comment by paragi** [comment]
Hi Karimhb

Thank you for the effort of reporting an issue. I appreciate that. 

Please understand, that the software is developed for free in out spare time, for your benefit.
To do that, we need the support of the community (you) 
That support includes well documented bug reporting. Without it, we cant improve the quality.
But since it is rather time-consuming, it is important that you create a test case and document the erroneous result. 
Otherwise we developers might spend a lot of time and resources in vain.

I took some time off to test your claim.
I set up the example server, and a php script with the following line in the script:

`setcookie("AAA", "value", -1, '/', ".localhost");`
Note the added comma.

In firefox I turned on the developer window. Displayed cookies:
Response-cookies	
AAA	
domain	.localhost
path	/
value	value

As you can see, the “.” is preserved.

To me that indicates that you didn't take the time to do a proper test of your own code, before you submitted an issue report. 
I and Apollon77 have spend time researching your problem, that could have been spend improving the software.

Please don't stop submitting issue reports. But please do you homework.

Best regards

**Comment by karimhb** [comment]
Hi Paragi,

I am happy to help. This is why I started this issue in the first place. I appreciate your time and effort in developing such a great tool. I don't think the comma was the issue. The cookie wouldn't have been set at all without the comma, this was a random quick example and I missed the comma on github.

Here are the results in both cases on same server and same browser with:
`setcookie("AAA", "value", 1520921941, '/', ".localhost")`

**ROW PHP**
Cookie is set @ .localhost (with the dot)

```
{
HTTPS: "on",
HTTP_CONNECTION: "close",
HTTP_CACHE_CONTROL: "max-age=0",
HTTP_USER_AGENT: "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.108 Safari/537.36",
HTTP_UPGRADE_INSECURE_REQUESTS: "1",
HTTP_ACCEPT: "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8",
HTTP_ACCEPT_ENCODING: "gzip, deflate, br",
HTTP_ACCEPT_LANGUAGE: "en-GB,en;q=0.9,en-US;q=0.8,en-AU;q=0.7,ar;q=0.6",
HTTP_COOKIE: "AAA=value",
PATH: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
SERVER_SIGNATURE: "",
SERVER_SOFTWARE: "Apache/2.4.18 (Ubuntu) mod_fcgid/2.3.9 OpenSSL/1.0.2g",
SERVER_PORT: "443",
REQUEST_SCHEME: "https",
CONTEXT_PREFIX: "",
REMOTE_PORT: "39626",
GATEWAY_INTERFACE: "CGI/1.1",
SERVER_PROTOCOL: "HTTP/1.0",
REQUEST_METHOD: "GET",
QUERY_STRING: "",
REQUEST_URI: "/test.php",
SCRIPT_NAME: "/test.php",
PHP_SELF: "/test.php",
REQUEST_TIME_FLOAT: 1520722298.056,
REQUEST_TIME: 1520722298,
}
```

**SPHP 4.3**
Cookie is set @ localhost (without the dot)

```
{
HTTP_COOKIE: "AAA=value",
HTTP_ACCEPT_LANGUAGE: "en-GB,en;q=0.9,en-US;q=0.8,en-AU;q=0.7,ar;q=0.6",
HTTP_ACCEPT_ENCODING: "identity",
HTTP_ACCEPT: "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8",
HTTP_USER_AGENT: "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.108 Safari/537.36",
HTTP_UPGRADE_INSECURE_REQUESTS: "1",
HTTP_CACHE_CONTROL: "max-age=0",
HTTP_CONNECTION: "upgrade",
HTTP_COOKIE_PARSE_RAW: "AAA=value",
SERVER_PROTOCOL: "HTTP/1.1",
REQUEST_METHOD: "GET",
QUERY_STRING:  "",
REQUEST_URI: "/test.php",
REMOTE_PORT: 45874,
SCRIPT_NAME: "/test.php",
DOCUMENT_ROOT: "/home/node/dist",
PHP_SELF: "/test.php",
SCRIPT_FILENAME: "/home/node/dist/test.php",
PATH_TRANSLATED: "/",
GATEWAY_INTERFACE: "PHP preburner 0.1.3",
SERVER_SOFTWARE: "PHP Appilation Server using Node.js and WS Websockets",
SERVER_SIGNATURE: "PHP Appilation Server using Node.js and WS Websockets Server with PHP preburner 0.1.3 at localhost:3010",
}
```

**Comment by karimhb** [comment]
Hey,

I just signed the petition "Human Rights Campaign: Justice for Maha
Almutairi" and wanted to see if you could help by adding your name.

Our goal is to reach 75,000 signatures and we need more support. You can
read more and sign the petition here:

http://chng.it/XcW84BPKJr

Thanks!
Kareem
